services:
  db:
    image: postgres:16-bullseye
    restart: always
    shm_size: 128mb
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: "syntax_admin"
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: "ai_assistant"
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ai_assistant -U syntax_admin"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    secrets:
      - db_password
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    working_dir: /home/backend
    build: .
    command: bash -c "uvicorn api.server:server --reload --host 0.0.0.0 --port 3100"
    ports:
      - "3100:3100"
    env_file: "../.env"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    volumes:
      - ./api:/home/backend/api
volumes:
  db_data:
secrets:
  db_password:
    file: ./db_password.txt