servies:
  db:
    image: postgres:16-bullseye
    restart: always
    shm_size: 128mb
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "syntax_admin"
      POSTGRES_PASSWORD: /run/secrets/db_password
      POSTGRES_DB: "ai_assistant"
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ai_assistant -U syntax_admin"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    secrets:
      - db_password
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
secrets:
  db_password:
    file: db_password.txt